### ISSUE TITLE
Ebook titles

### ISSUE THREAD

**Issue by iliakan** [KenjiI/javascript-tutorial-ja#5]
Please translate the following titles:

Part I. The JavaScript Language
340+ pages, PDF + EPUB

Part II. Browser: Document, Events, Interfaces
220+ pages, PDF + EPUB

Part III. Additional Articles (Animations, Async/Await, etc.)
150+ pages, PDF + EPUB

Parts I && II together
2xPDF + 2xEPUB, (560+ pages)

Full Tutorial (all 3 parts)
3xEPUB + 3xPDF, (710+ pages)

P.S. Please leave the pages count (like 710+) "as is", not translated, if possible.

**Comment by KenjiI** [comment]
Here is the translations. Thanks.

パート 1. JavaScript 言語
340+ ページ, PDF + EPUB

パート 2. ブラウザ: ドキュメント, イベント, インタフェース
220+ ページ, PDF + EPUB

パート 3. その他の記事 (アニメーション, Async/Await, 等.)
150+ ページ, PDF + EPUB

パート 1 && 2 合わせて
2xPDF + 2xEPUB, (560+ ページ)

完全なチュートリアル (3 パートすべて)
3xEPUB + 3xPDF, (710+ ページ)
