### ISSUE TITLE
バイナリ +

### ISSUE THREAD

**Issue by azu** [KenjiI/javascript-tutorial-ja#9]
binary `+` は 二項 `+`(演算子) の方が適切かなと思います。

単項 `+` と対となるように 二項 `+` としたほうがわかりやすいと思います。

```diff
- 用語： “単項演算子”、 “バイナリ”、 “オペランド”
+ 用語： “単項演算子”、 “二項演算子”、 “オペランド”
```

- https://ja.javascript.info/operators
- https://javascript.info/operators
- https://ja.wikipedia.org/wiki/%E6%BC%94%E7%AE%97%E5%AD%90#%E4%BA%8C%E9%A0%85%E6%BC%94%E7%AE%97%E5%AD%90

> 演算子が2つのオペランドを持つ場合は バイナリ です。同じマイナスもバイナリ形式で同様に存在します:

この辺を見ていて、2進数的な[バイナリ](https://ja.wikipedia.org/wiki/%E3%83%90%E3%82%A4%E3%83%8A%E3%83%AA)の話に見えてしまうと思うので。

**Comment by KenjiI** [comment]
仰るとおり単項と対となるよう、二項演算子とするのが適切ですね。
ありがとうございます。

**Comment by KenjiI** [comment]
修正しました。問題あれば再オープンします。
